### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by zeinalii** [data301-2020-winter1/course-project-solo_325#1]
## High priority (must-fix)

- [x] add a structure to your report. It is better to have an introduction that gives the reader some information about the data and your question. 

- [x] Add a section called analysis, and explain why exactly you chose that specific method of analysis to answer your questions. Why do you think that method of visualization would help you to answer the questions.

- [x] Just graphs alone do not answer your questions. You need to explain how those visualizations answer your questions. Try to explain the plots.

- [x] Printing the dataset alone does not explain the data. You need to add a section called dataset, and explain the data. What are the columns and what do they show?

- [x] Add a section called conclusion and summarize your findings and analysis method. 

## Medium priority (should fix)

 - [ ] You have used absolute addresses in your code. Change them to relative addresses.

**Comment by robroskie** [comment]
High priority fixes have been completed.
